spring:
    profiles:
      active:
      - dev
---
spring:
  profiles: dev
  application:
    name: springcloudSGG-config-cyx-dev
---
spring:
  profiles: test
  application:
    name: springcloudSGG-config-cyx-test
